# Site settings
title: JU's Blog
SEOTitle: JU's Blog
header-img: img/home-bg.jpg
email: 13169703137@163.com
description: ""
keyword: ""
url: "https://zhengyucheng.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'

inserver: true

# MathJax
mathjax: true

# SNS settings
RSS: true
#weibo_username:     YanWQ-monad
#zhihu_username:     YanWQ-monad
#github_username:    YanWQ-monad
#twitter_username:   YanWQ-monad
#facebook_username:  YanWQ-monad
#google_plus_id: 112757454778156334087
#qq_id: 643172561

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge

# Analytics
#ba_track_id: a105f7a51093c08c1aaa8bec96428621
#ga_track_id: UA-106147042-1

# Disqus
#disqus_username: monadblog

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "OH, DUCK"
sidebar-avatar: /img/Avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
  {
    title: "Monad",
    href : "https://blog.monad.ga"
  },
  {
    title: "Ghastlcon",
    href : "https://ghastlcon.cf"
  },
  {
    title: "Ufowoqqqo",
    href : "https://Ufowoqqqo.github.io"
  },
  {
    title: "wyy",
    href : "http://www.cnblogs.com/littlewyy",
  },
  {
    title: "zqy",
    href : "http://www.cnblogs.com/yiyiyizqy",
  },
  {
    title: "aspe",
    href : "http://yhf4aspe.blog.163.com"
  }
]
